CREATE TABLE `ukmtv` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `season` int(4) NOT NULL,
  `pl_id` int(6) NOT NULL,
  `type` enum('innslag','reportasje') COLLATE utf8mb4_danish_ci NOT NULL DEFAULT 'innslag',
  `b_id` int(11) NOT NULL,
  `blog_id` int(11) DEFAULT NULL,
  `status_progress` enum('registering','registered','converting','converted','store','transferring','transferred','archive','archiving','complete','crashed','does_not_exist') COLLATE utf8mb4_danish_ci NOT NULL DEFAULT 'registering',
  `status_first_convert` enum('convert','converting','complete') COLLATE utf8mb4_danish_ci DEFAULT NULL,
  `status_final_convert` enum('convert','converting','complete') COLLATE utf8mb4_danish_ci DEFAULT NULL,
  `status_archive` enum('convert','converting','complete') COLLATE utf8mb4_danish_ci DEFAULT NULL,
  `file_name_store` varchar(255) COLLATE utf8mb4_danish_ci DEFAULT NULL,
  `file_name` varchar(200) COLLATE utf8mb4_danish_ci NOT NULL DEFAULT '',
  `file_path` varchar(255) COLLATE utf8mb4_danish_ci NOT NULL DEFAULT '',
  `file_type` varchar(6) COLLATE utf8mb4_danish_ci DEFAULT NULL,
  `file_duration` varchar(10) COLLATE utf8mb4_danish_ci NOT NULL DEFAULT '00:00:00',
  `file_width` varchar(16) COLLATE utf8mb4_danish_ci NOT NULL DEFAULT '',
  `file_height` varchar(16) COLLATE utf8mb4_danish_ci NOT NULL DEFAULT '',
  `OLD_nicename` text COLLATE utf8mb4_danish_ci NOT NULL,
  `OLD_band_related` enum('true','false') COLLATE utf8mb4_danish_ci NOT NULL DEFAULT 'true',
  `touch` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `attempt` enum('first','second','cancelled') COLLATE utf8mb4_danish_ci NOT NULL DEFAULT 'first',
  `admin_notice` enum('false','true') COLLATE utf8mb4_danish_ci NOT NULL DEFAULT 'false',
  `pixel_format` varchar(20) COLLATE utf8mb4_danish_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_danish_ci;